version: '3'

services:
  api:
    build: .
    command: mix phx.server
    depends_on:
    - db
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/mini_investor_api_dev
      MIX_ENV: dev
      PORT: '4000'
    ports:
    - '4000:4000'
    volumes:
    - .:/app
  db:
    image: postgres:11.1-alpine
    volumes:
    - pgdata:/var/lib/postgresql/data
    ports:
    - '5433:5432'
  web:
    image: baruh/mini-investor-ui:v0.1
    ports:
    - '8080:80'
    depends_on:
    - api
volumes:
  pgdata:
